name: Secret scan

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  secret-scan:
    name: Secret scan
    runs-on: ubuntu-latest
    steps:
      - uses: Nucleo-Estudantes-Informatica-ISEP/.github/.github/actions/secret-scan@master
