name: Reusable Dependency Review

on:
  workflow_call:

jobs:
  dependency-review:
    name: Dependency review
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Review dependency changes
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
